create table bill_item
(
    id       bigint generated by default as identity
        primary key,
    quantity integer not null,
    bill_id  bigint
        constraint fkcf0kpt07c9onbtvnttajk3skx
            references bill,
    cloth_id bigint
        constraint fkdqqiqtrd94h2t21exsgdrcfka
            references cloth
);

alter table bill_item
    owner to postgres;