INSERT INTO public.cloth (name, price, stock, description, image) VALUES
                                                                      ('Ao da', '1000000', 50, 'Ao da mang to tuyet dep', ''),
                                                                      ('Ao thun', '200000', 100, 'Ao thun cotton mem mai', ''),
                                                                      ('Quan jeans', '500000', 75, 'Quan jeans nam thoi trang', ''),
                                                                      ('Vay maxi', '300000', 60, 'Vay maxi cho phu nu', ''),
                                                                      ('Ao khoac', '800000', 30, 'Ao khoac da nang', ''),
                                                                      ('Dam maxi', '400000', 40, 'Dam maxi cho ngay he', ''),
                                                                      ('Ao so mi', '250000', 80, 'Ao so mi nam', ''),
                                                                      ('Quan short', '150000', 90, 'Quan short cho mua he', ''),
                                                                      ('Ao len', '600000', 20, 'Ao len ấm áp cho mùa đông', ''),
                                                                      ('Vay ngắn', '350000', 55, 'Vay ngắn xinh xắn', ''),
                                                                      ('Ao thun tay dai', '220000', 70, 'Ao thun tay dai thoải mái', ''),
                                                                      ('Quan tây', '700000', 45, 'Quan tây cho công sở', ''),
                                                                      ('Ao khoac da', '1200000', 25, 'Ao khoac da cao cấp', ''),
                                                                      ('Dam suong', '450000', 35, 'Dam suong thanh lich', ''),
                                                                      ('Ao phao', '900000', 15, 'Ao phao giữ ấm', ''),
                                                                      ('Quan legging', '300000', 65, 'Quan legging thoải mái', ''),
                                                                      ('Ao thun in hinh', '180000', 85, 'Ao thun in hinh vui nhon', ''),
                                                                      ('Vay midi', '400000', 50, 'Vay midi cho phu nu', ''),
                                                                      ('Ao khoac bomber', '700000', 30, 'Ao khoac bomber thoi trang', ''),
                                                                      ('Dam xoe', '350000', 55, 'Dam xoe cho buoi tiệc', ''),
                                                                      ('Ao thun cổ tròn', '200000', 100, 'Ao thun cổ tròn cơ bản', ''),
                                                                      ('Quan jogger', '250000', 80, 'Quan jogger thoải mái', ''),
                                                                      ('Ao vest', '1200000', 20, 'Ao vest cho nam', ''),
                                                                      ('Vay ôm', '500000', 40, 'Vay ôm quyến rũ', ''),
                                                                      ('Ao khoac trench', '950000', 25, 'Ao khoac trench thanh lich', ''),
                                                                      ('Dam hoa', '300000', 60, 'Dam hoa cho mùa hè', ''),
                                                                      ('Ao thun cổ bẻ', '220000', 70, 'Ao thun cổ bẻ nam', ''),
                                                                      ('Quan culottes', '400000', 50, 'Quan culottes thoải mái', ''),
                                                                      ('Ao hoodie', '600000', 30, 'Ao hoodie cho mùa đông', ''),
                                                                      ('Vay xòe', '350000', 55, 'Vay xòe dễ thương', ''),
                                                                      ('Ao khoac lông', '800000', 15, 'Ao khoac lông sang trọng', ''),
                                                                      ('Dam body', '450000', 35, 'Dam body quyến rũ', ''),
                                                                      ('Ao thun tay ngắn', '200000', 90, 'Ao thun tay ngắn thoải mái', ''),
                                                                      ('Quan ống rộng', '300000', 65, 'Quan ống rộng thời trang', '');