create table if not exists role
(
    id               bigint generated by default as identity
        constraint role_pk
            primary key,
    role_name        varchar not null,
    role_description varchar,
    created_date     date default now(),
    updated_date     date default now(),
    deleted_date     date
);