create table role_user
(
    id      bigint generated by default as identity (minvalue 0)
        constraint role_user_pk
            primary key,
    user_id bigint not null
        constraint role_user_user_id_fk
            references "user",
    role_id bigint not null
        constraint role_user_role_id_fk
            references role
);

