INSERT INTO public.permission (permission_code, permission_description) VALUES ('GET_USERS', 'read users');
INSERT INTO public.permission (permission_code, permission_description) VALUES ('DELETE_USER', 'delete user');
INSERT INTO public.permission (permission_code, permission_description) VALUES ('CREATE_USER', 'create user');
INSERT INTO public.permission (permission_code, permission_description) VALUES ('UPDATE_USER', 'upder user');
INSERT INTO public.permission (permission_code, permission_description) VALUES ('GET_CLOTH', 'read cloth');
INSERT INTO public.permission (permission_code, permission_description) VALUES ('DELETE_CLOTH', 'delete cloth');
INSERT INTO public.permission (permission_code, permission_description) VALUES ('CREATE_CLOTH', 'create cloth');
INSERT INTO public.permission (permission_code, permission_description) VALUES ('UPDATE_CLOTH', 'update cloth');
INSERT INTO public.permission (permission_code, permission_description) VALUES ('CREATE_BILL', 'create bill');
